import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faClockRotateLeft,
  faFire,
  faFloppyDisk,
  faGear,
  faHouse,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faRotate,
  faTicket,
  faTriangleExclamation,
  faWifi,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faClockRotateLeft,
  faFire,
  faFloppyDisk,
  faGear,
  faHouse,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faRotate,
  faTicket,
  faTriangleExclamation,
  faWifi,
)

export {
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faClockRotateLeft,
  faFire,
  faFloppyDisk,
  faGear,
  faHouse,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faRotate,
  faTicket,
  faTriangleExclamation,
  faWifi,
}
