import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClockRotateLeft,
  faEye,
  faFire,
  faFloppyDisk,
  faGear,
  faInbox,
  faLayerGroup,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faTicket,
  faTriangleExclamation,
  faWifi,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClockRotateLeft,
  faEye,
  faFire,
  faFloppyDisk,
  faGear,
  faInbox,
  faLayerGroup,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faTicket,
  faTriangleExclamation,
  faWifi,
)

export {
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBell,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClockRotateLeft,
  faEye,
  faFire,
  faFloppyDisk,
  faGear,
  faInbox,
  faLayerGroup,
  faMagnifyingGlass,
  faPlus,
  faRobot,
  faTicket,
  faTriangleExclamation,
  faWifi,
}
